# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: 阅读更多

# Sidebar
author:
  name: Sanonz
  work: Web Developer &amp; Designer
  location: Shenzhen, China
# widgets:
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
# index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
# show_count: false
# archive_type: 'monthly'

# Disqus 
disqus:
  enable: true
  shortname: name    #your name
  # count: true

#User Profiles
profile:
  twitter:
  google_plus:
  github:

# Miscellaneous
google_analytics:
favicon: /favicon.png
fb_admins:
fb_app_id:
